### ISSUE TITLE
The `mergeClientRects` resolution of the `block-contains` & `block-is-contained` edge case

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#189]
### TL;DR;
When the content contains elements with the `vertical-align` style - the `mergeClientRects` can unexpectedly preserve selection only over it, ignoring everything before.

[**_Interactive playground_**](https://playcode.io/2263001)

[**_Skip to the question_**](https://arc.net/l/quote/ribfrmyc)

App:

https://github.com/user-attachments/assets/729e5702-7988-4626-8fbe-252d0889ce12

`@recogito/text-annotator` sandbox:

https://github.com/user-attachments/assets/eb963ac4-ca22-4f36-81e2-b7ab90d77c80

## Issue
I tracked down that the "dismissal" of the content before the "super" element happens in the `mergeClientRects` function. 

It establishes the `block-is-contained` relation between the "super" element rect and the rects on the left:
| Rects | Relation |
|--------|--------|
| ![Image](https://github.com/user-attachments/assets/cccea4be-650a-4501-b7f1-bef083a18ef5) |  ![Image](https://github.com/user-attachments/assets/3713ef36-731a-4dce-979f-1eedb09b7f4a) | 

https://github.com/recogito/text-annotator-js/blob/5b9abad31724db14d473f7d363b295a967cd93b7/packages/text-annotator/src/utils/mergeClientRects.ts#L51-L54

After, that the merging code picks the rect with the smaller width: 

![Image](https://github.com/user-attachments/assets/7e46ab72-e91b-4208-8ef8-87aac818875b)

So the whole left part rect gets replaced with the "super" element rect!

https://github.com/recogito/text-annotator-js/blob/5b9abad31724db14d473f7d363b295a967cd93b7/packages/text-annotator/src/utils/mergeClientRects.ts#L94-L101

## Reproduction
The issue can be reproduced in the `@recogito/text-annotator` sandbox ([**_Interactive playground_**](https://playcode.io/2263001)):
```html
<p>In 2020, the U.S. unemployment rate rose from a longtime record low of 3.5 percent in February to 14.7 percent in April. This represents a loss of 30 million jobs or about 18 percent of the labor force prior to the COVID-19 
<span class="footnote-ref-tail">pandemic.
	<a class="footnote-ref" name="footnote-ref-1" href="#footnote-1">1</a>
</span> To put this total in context
</p>
```
```css
.footnote-ref-tail {
  white-space: nowrap;
}

.footnote-ref {
  display: inline-block;
  min-width: 20px;
  background-clip: content-box;
  vertical-align: super;
  color: #5f01df;
  font-size: 14px;
  font-style: normal;
  font-weight: bold;
  line-height: 17px;
  text-align: center;
  text-decoration: none;
  cursor: pointer;
  position: relative;
  top: 5px;
}

.footnote-ref::before {
  content: '[';
}
.footnote-ref::after {
  content: ']';
}
```

## Question
Should we consider _using the wider rect_ instead of the smaller one as a replacement target? That way we'll pick the container rect instead of the one that's being contained. It sounds like a more sensible approach to me 🤔
