### ISSUE TITLE
Highlight API

### ISSUE THREAD

**Issue by rsimon** [recogito/text-annotator-js#26]
The [Highlight API](https://developer.mozilla.org/en-US/docs/Web/API/Highlight) seems to be pretty much universally available now. It would be interesting to see a proof of concept for an alternative Highlighter implementation that uses this API instead of  Canvas-based rendering. This would, very likely, also eliminate the annotation drift problem we currently have.

**Comment by oleksandr-danylchenko** [comment]
*Leaving reference to the discussion where ability to emulate the `border-bottom` was suggested - https://github.com/recogito/text-annotator-js/pull/19#issuecomment-1948217053

> Re underline: yes, text-decoration: underline works. But what I would have wanted was a bottom border underneath the highlight itself (as used to be [the default style in RecogitoJS](https://raw.githubusercontent.com/recogito/recogito-js/main/screenshot.png)). In CSS terms that would have been something like border-bottom: 1px solid orange. Alas, that's now out of the question.

Maybe the "border" style can be emulated by using the `text-underline-offset` and `text-decoration-color`. Playground - https://developer.mozilla.org/en-US/play?id=nYCSiAB9X5gJuEpKkB9wy6LlQp51l2UGHyZcVNOPkXDHQaOjg26ZScZrwTF8%2BIUvoZhNvoUyYVg%2Fz2BX

```css
::highlight(rainbow-color-1) {
  background-color: rgba(235, 149, 50, 0.3);
  text-decoration: underline;
  text-underline-offset: 6px;
  text-decoration-color: orange;
}
```
![image](https://github.com/recogito/text-annotator-js/assets/68850090/81941749-2371-4b1f-99e1-02c664db7587)
